### ISSUE TITLE
错误率会超过100%(●—●)

### ISSUE THREAD

**Issue by arisskz6** [garfeng/xnhe#1]
![1517917337306](https://user-images.githubusercontent.com/17875969/35858340-071e1b6c-0b77-11e8-9c9f-508df2cd380e.png)
andriod 8.0/chrome

**Comment by garfeng** [comment]
确实会如此……工具把同一个字的反复错误叠加计算，只要不改过来就一直叠加……

这个问题我有空处理下。
谢谢使用何报告~


## 已解决~
