### ISSUE TITLE
手机上玩的话，建议加个“速度”选项

### ISSUE THREAD

**Issue by zodensu** [garfeng/xnhe#3]
不过，希望设置一个速度过多少多少并且准确率达到70%，这样子才能换段。毕竟手机打字还是要求准确率的好，手机打字没多少人能打得很快😀
另外，手机击键的统计也不准，不知道您是不是用的和消逝大神的统计方法( σ'ω')σ

**Comment by garfeng** [comment]
速度的条件加上去了。
击键无法统计准确。不同输入法都不一样。先只能这样了。
